name: BRPartyMode
version: 1.0
author: Steven
main: io.github.steaf23.brpartymode.BRPartyMode
api-version: 1.19

permissions:
  bingo.admin:
    description: Access all commands and features.
    default: op
    children:
      bingo.settings: true # used for accessing all settings in ./bingo
      bingo.manager: true # used to create and remove cards and item list in the card creator
  bingo.player:
    description: Players can join teams and play games.
    default: true

commands:
  bingo: