name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build release JAR
      run: ./gradlew clean build shadowJar

    - name: Get version from build.gradle
      id: get_version
      run: |
        VERSION=$(grep "version = " BingoReloaded/build.gradle | cut -d "'" -f 2)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Rename JAR files
      run: |
        cd BingoReloaded/build/libs
        for file in *.jar; do
          if [[ $file == *"-all.jar" ]]; then
            mv "$file" "BingoReloaded-${{ steps.get_version.outputs.version }}.jar"
          fi
        done

    - name: Upload release assets
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./BingoReloaded/build/libs/BingoReloaded-${{ steps.get_version.outputs.version }}.jar
        asset_name: BingoReloaded-${{ steps.get_version.outputs.version }}.jar
        asset_content_type: application/java-archive

    - name: Upload artifacts (manual dispatch)
      if: github.event_name == 'workflow_dispatch'
      uses: actions/upload-artifact@v4
      with:
        name: BingoReloaded-release-${{ steps.get_version.outputs.version }}
        path: |
          BingoReloaded/build/libs/BingoReloaded-${{ steps.get_version.outputs.version }}.jar
        retention-days: 90